(load "~/.emacs.d/local/rc.el")

(rc/require-theme 'gruber-darker)
(rc/require 'simpleclip)
(rc/require 'multiple-cursors)
(rc/require 'move-text)
(rc/require 'magit)
(rc/require 'rainbow-mode)
(rc/require 'smex)
(rc/require 'mood-line)
