(add-hook 'c-mode-hook           'rc/turn-on-paredit)
(add-hook 'c++-mode-hook         'rc/turn-on-paredit)
(add-hook 'simpc-mode-hook       'rc/turn-on-paredit)
(add-hook 'emacs-lisp-mode       'rc/turn-on-paredit)
(add-hook 'markdown-mode-hook    'rc/turn-on-paredit)
(add-hook 'text-mode-hook        'rc/turn-on-paredit)
(add-hook 'python-mode-hook      'rc/turn-on-paredit)
(add-hook 'emacs-lisp-mode-hook  'rc/turn-on-paredit)

(add-hook 'c-mode-hook           'rc/set-up-whitespace-handling)
(add-hook 'c++-mode-hook         'rc/set-up-whitespace-handling)
(add-hook 'simpc-mode-hook       'rc/set-up-whitespace-handling)
(add-hook 'emacs-lisp-mode       'rc/set-up-whitespace-handling)
(add-hook 'markdown-mode-hook    'rc/set-up-whitespace-handling)
(add-hook 'text-mode-hook        'rc/set-up-whitespace-handling)
(add-hook 'python-mode-hook      'rc/set-up-whitespace-handling)
(add-hook 'emacs-lisp-mode-hook  'rc/set-up-whitespace-handling)
