(load "~/.emacs.d/_base/melpa.el")
(load "~/.emacs.d/_base/functions.el")
(load "~/.emacs.d/_base/packages.el")
(load "~/.emacs.d/_base/garbage.el")
(load "~/.emacs.d/_base/ui.el")
(load "~/.emacs.d/_base/basic.el")
(load "~/.emacs.d/_base/compilation-buffer.el")
(load "~/.emacs.d/_base/minibuffer.el")
(load "~/.emacs.d/_base/package-settings.el")
; (load "~/.emacs.d/_base/mac.el")
(load "~/.emacs.d/_base/keymaps.el")
(load "~/.emacs.d/_base/lsp.el")
(load "~/.emacs.d/_base/custom.el")
(load "~/.emacs.d/_base/hooks.el")
(load "~/.emacs.d/_base/ssh.el")
