;;; functions.el --- lr/* helper functions -*- lexical-binding: t; -*-

(defun lr/toggle-theme ()
  (interactive)
  (diredfl-global-mode 1)
  (let* ((light 'lr_solarized_light)
         (dark  'lr_gruberdarker)
         (current (car custom-enabled-themes))
         (next (if (eq current light) dark light)))
    (mapc #'disable-theme custom-enabled-themes)
    (load-theme next t)))

(defun lr/delete-line ()
  (interactive)
  (save-excursion
    (delete-region
     (progn (forward-visible-line 0) (point))
     (progn (forward-visible-line 1) (point)))))

(defun lr/duplicate-line ()
  (interactive)
  (let ((column (- (point) (point-at-bol)))
        (line (let ((s (thing-at-point 'line t))) (if s (string-remove-suffix "\n" s) ""))))
    (move-end-of-line 1)
    (newline)
    (insert line)
    (move-beginning-of-line 1)
    (forward-char column)))

(defun lr/default-theme ()
  (interactive)
  (whitespace-mode 0)
  (diredfl-global-mode 0)
  (mapc #'disable-theme custom-enabled-themes))

(defun lr/minibuffer-history-keys ()
  (define-key minibuffer-local-map (kbd "C-n") #'next-history-element)
  (define-key minibuffer-local-map (kbd "C-p") #'previous-history-element))

(defun lr/modern ()
  (lr/use-font "Comic Code-16")
  (lr/theme 'lr_gruberdarker)
  (mood-line-mode 1)
  (vertico-mode 1)
  (marginalia-mode 1)
  (global-whitespace-mode 0)
  (vertico-flat-mode 0)
  (set-fringe-mode 0)
  (lr/line-relative)
  ;; (remove-hook 'minibuffer-setup-hook #'lr/minibuffer-history-keys)
  )

(defun lr/legacy ()
  (lr/default-theme)
  (eglot-shutdown-all)
  (cond ((eq system-type 'windows-nt) (lr/disable-font))
        ((eq system-type 'darwin)     (lr/use-font "Comic Code-16"))
        ((eq system-type 'gnu/linux)  (lr/disable-font)))
  (global-whitespace-mode 0)
  (mood-line-mode 1)
  (company-mode 0)
  (vertico-mode 1)
  (vertico-flat-mode 1)
  (marginalia-mode 0)
  (lr/line-off)
  (set-fringe-mode '(8 . 8))
  ;; (add-hook 'minibuffer-setup-hook #'lr/minibuffer-history-keys)
  )

(defun lr/toggle-ui () (interactive) (setq lr/switch (not lr/switch)) (if lr/switch (lr/modern) (lr/legacy)) (message ""))

(defun lr/disable-font ()
  (interactive)
  (cond ((eq system-type 'darwin)
         (let ((default-font (or (cdr (assoc 'font default-frame-alist)) "Menlo-14")))
           (set-frame-font default-font t t)
           (setq-default line-spacing nil)
           (dolist (buf (buffer-list))
             (with-current-buffer buf
               (force-window-update (get-buffer-window buf)))))))
  (set-frame-font nil t t)
  (setq-default line-spacing nil)
  (dolist (buf (buffer-list))
    (with-current-buffer buf
      (force-window-update (get-buffer-window buf)))))

(defun lr/use-font (font)
  (when (member (car (split-string font "-")) (font-family-list))
    (set-frame-font font t t)
    (setq-default line-spacing 0)
    (dolist (buf (buffer-list))
      (with-current-buffer buf
        (force-window-update (get-buffer-window buf))))))

(defvar lr/font-list'("Menlo-16" "Iosevka-16" "Lilex Nerd Font Mono-16" "Consoleet Darwin Smooth-18" "Comic Code-16"))
(defun lr/enable-font ()
  (interactive)
  (let* ((input (completing-read "Choose font: " lr/font-list nil nil)) (font input))
    (when (member (car (split-string font "-")) (font-family-list)) (lr/use-font font))))

(defun lr/theme (theme)
  (interactive (list (intern (completing-read "Theme: " (custom-available-themes)))))
  (mapc #'disable-theme custom-enabled-themes)
  (setq custom-safe-themes t)
  (load-theme theme t))

(defun lr/on_save () (interactive) (add-to-list 'write-file-functions 'delete-trailing-whitespace))
(defun lr/cut () (interactive) (simpleclip-cut (region-beginning) (region-end)) (deactivate-mark) (sit-for 1))
(defun lr/copy () (interactive) (simpleclip-copy (region-beginning) (region-end)) (deactivate-mark) (sit-for 1))
(defun lr/paste () (interactive) (simpleclip-paste) (deactivate-mark) (sit-for 1))

(defun lr/toggle-mini-buffer-mode ()
  (interactive)
  (if (bound-and-true-p vertico-flat-mode) (progn (vertico-flat-mode -1) (marginalia-mode 1) (message "Use Vertical"))
    (progn (vertico-flat-mode 1) (setq vertico-count-format nil) (marginalia-mode -1) (message "Use Horizontal"))))

(defun lr/colorize-compilation-buffer ()
  (read-only-mode 'toggle)
  (ansi-color-apply-on-region compilation-filter-start (point))
  (read-only-mode 'toggle))

(defun lr/toggle-buffer (buffer-name)
  (interactive "Buffer name: ")
  (let ((buffer (get-buffer buffer-name)))
    (if (and buffer (get-buffer-window buffer))
        (delete-window (get-buffer-window buffer))
      (switch-to-buffer-other-window (get-buffer-create buffer-name)))))

(defun lr/toggle-config ()
  (interactive)
  (let* ((file user-init-file) (buffer (find-file-noselect file)))
    (if (get-buffer-window buffer) (delete-window (get-buffer-window buffer)) (switch-to-buffer-other-window buffer))))
(defun lr/toggle-scratch-buffer () (interactive) (lr/toggle-buffer "*scratch*"))
(defun lr/toggle-compilation-buffer () (interactive) (lr/toggle-buffer "*compilation*"))
(defun lr/toggle-system () (interactive) (if (and (boundp 'vertico-mode) vertico-mode) (lr/legacy) (lr/modern)))
(defun lr/open_config() (interactive) (find-file user-init-file))

(defun lr/find-corresponding-file ()
  (interactive)
  (let* ((name (buffer-file-name))
         (base (when name (file-name-sans-extension name)))
         (ext  (and name (file-name-extension name)))
         target)
    (when name
      (setq target
            (cond ((member ext '("c" "cpp" "cc" "cxx")) (or (concat base ".h") (concat base ".hpp")))
                  ((member ext '("h" "hpp"))
                   (cond ((file-exists-p (concat base ".c"))   (concat base ".c"))
                         ((file-exists-p (concat base ".cpp")) (concat base ".cpp"))
                         ((file-exists-p (concat base ".cc"))  (concat base ".cc"))))
                  (t nil)))
      (if (and target (file-exists-p target)) (find-file target) (message "No corresponding file found")))))

(defun lr/update-line-number-font-size ()
  (interactive)
  (let ((base-height (face-attribute 'default :height))
        (scale-factor (if (boundp 'text-scale-mode-amount) (expt text-scale-mode-step text-scale-mode-amount) 1)))
    (face-remap-add-relative 'line-number :height (round (* base-height scale-factor)))
    (face-remap-add-relative 'line-number-current-line :height (round (* base-height scale-factor)))))
(defun lr/font-increase() (interactive) (text-scale-increase 1) (lr/update-line-number-font-size))
(defun lr/font-decrease() (interactive) (text-scale-decrease 1) (lr/update-line-number-font-size))

(defun lr/line-normal() (interactive) (menu-bar--display-line-numbers-mode-absolute))
(defun lr/line-relative() (interactive) (menu-bar--display-line-numbers-mode-relative))
(defun lr/line-off() (interactive) (menu-bar--display-line-numbers-mode-none))
(defun lr/toggle-line-numbers ()
  (interactive)
  (cond
   ((eq display-line-numbers 'relative) (lr/line-normal))
   ((eq display-line-numbers t)         (lr/line-relative))
   (t                                   (lr/line-relative))))

(defun lr/toggle-whitespace ()
  (interactive)
  (if (bound-and-true-p global-whitespace-mode) (global-whitespace-mode -1) (global-whitespace-mode 1)))

(defun lr/compile-minibuffer-setup ()
  (when (eq this-command 'compile)
    (local-set-key (kbd "C-n") 'next-history-element)
    (local-set-key (kbd "C-p") 'previous-history-element)))

(defun lr/fido-minibuffer-setup ()
  (when (or fido-mode fido-vertical-mode)
    (local-set-key (kbd "C-s") 'next-history-element)
    (local-set-key (kbd "C-r") 'previous-history-element)
    (unless (eq this-command 'compile)
      (local-set-key (kbd "C-n") 'icomplete-forward-completions)
      (local-set-key (kbd "C-p") 'icomplete-backward-completions))))

(defun lr/vertico-flat-minibuffer-setup ()
  (when (or fido-mode vertico-flat-mode)
    (local-set-key (kbd "C-s") 'next-history-element)
    (local-set-key (kbd "C-r") 'previous-history-element)
    (unless (eq this-command 'compile)
      (local-set-key (kbd "C-n") 'icomplete-forward-completions)
      (local-set-key (kbd "C-p") 'icomplete-backward-completions))))

(defun lr/reload () (interactive) (load-file user-init-file) (message "Emacs reloaded."))
(defun lr/minibuffer-setup-combined () (lr/compile-minibuffer-setup) (lr/fido-minibuffer-setup))
(defun lr/remove-window-dividers ()
  (window-divider-mode -1)
  (dolist (frame (frame-list))
    (dolist (window (window-list frame))
      (set-window-parameter window 'window-divider-right-width 0)
      (set-window-parameter window 'window-divider-bottom-width 0))))

(defvar lr/transparent-enabled nil)
(defun lr/transparent ()
  (interactive)
  (setq lr/transparent-enabled (not lr/transparent-enabled))
  (if lr/transparent-enabled
      (progn
        (set-frame-parameter nil 'alpha 95)
        (add-to-list 'default-frame-alist '(alpha . 95))
        (message "Transparency enabled"))
    (progn
      (set-frame-parameter nil 'alpha 100)
      (setq default-frame-alist (assq-delete-all 'alpha default-frame-alist))
      (message "Transparency disabled"))))

(provide 'functions)
;;; functions.el ends here
